### ISSUE TITLE
Can't load the module from a script on another disk

### ISSUE THREAD

**Issue by zlataovce** [camprevail/pet-pet-gif#1]
```
Traceback (most recent call last):
  File "C:\Users\MK - Gaming PC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 607, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Project-Ludde\libs\cogs\fun.py", line 2, in <module>
    from petpetgif import petpet as petpetmaker
  File "C:\Users\MK - Gaming PC\AppData\Local\Programs\Python\Python38\lib\site-packages\petpetgif\petpet.py", line 6, in <module>
    package_dir = Path(os.path.relpath(__file__)).parent
  File "C:\Users\MK - Gaming PC\AppData\Local\Programs\Python\Python38\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'C:', start on mount 'E:'
```

**Comment by camprevail** [comment]
Thanks for the report. Should be fixed now.
